### ISSUE TITLE
pylddwrap 1.1.0 fails to handle statically linked libraries

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [Parquery/pylddwrap#12]
I have noticed that with the latest release of 1.1.0, the `lddwrap.list_dependencies` fails when using it on a statically linked library:

```
my_static_lib.so:
        statically linked
```

with the error message: 

> RuntimeError: Unexpected mem address. Expected to match ^\s*\(([^)]*)\)\s*$, but got: 'linked'

This makes sense because normally, for a shared library, this is what you would get:
 
```
my_share_lib.so:
        linux-lib.so.1 (0x00007fff4a9fe000)
        linux-lib2.so => path
```

so `statically linked` is being parsed in the way that `statically` is considered to be the file and the `linked` is considered to be a memory address which of course fails the regex match.

Do you think that it would make more sense to avoid proceeding to the parsing step if `ldd` tells us that it's a statically linked library? 

For the previous version, 1.0.1, it's happily reporting the following:

```
from pathlib import Path
import lddwrap
deps = lddwrap.list_dependencies(Path('my_static_lib.so'))
for dep in deps:
    print(dep.path)
    print(dep.found)
    print(dep.soname)

statically
True
None
```

The statically is definitely not a correct file path, but raising an exception does not feel right either as `ldd` doesn't fail itself.

**Comment by alexey-tereshenkov-oxb** [comment]
@mristin and thank you for this little package, it's very useful!

**Comment by mristin** [comment]
@alexey-tereshenkov-oxb thanks for reporting the issue! It is amazing what edge cases there are in the wild :-).

Could you please write me a full STDOUT that you get from ldd so that I can test?

**Comment by alexey-tereshenkov-oxb** [comment]
Hey thanks for pinging back! 

I've posted the ldd output in the issue body, it's just `statically linked`. As simple as it can possibly get! :)
That library wasn't supposed to be fed to ldd in the first place, but since it was, thought it would be worth sharing ;)

Also a traceback for your convenience:

```
dependencies = lddwrap.list_dependencies(path=binary_file, env=env)
File "/tmp/tmp.PsmdRTkgxw/env/lib/python3.6/site-packages/icontract/_checkers.py", line 396, in wrapper
result = func(*args, **kwargs)
File "/tmp/tmp.PsmdRTkgxw/env/lib/python3.6/site-packages/lddwrap/__init__.py", line 220, in list_dependencies
dependencies = _cmd_output_parser(cmd_out=out)  # type: List[Dependency]
File "/tmp/tmp.PsmdRTkgxw/env/lib/python3.6/site-packages/lddwrap/__init__.py", line 259, in _cmd_output_parser
dep = _parse_line(line=line)
File "/tmp/tmp.PsmdRTkgxw/env/lib/python3.6/site-packages/lddwrap/__init__.py", line 180, in _parse_line
mem_address=_strip_mem_address(text=parts[1]))
File "/tmp/tmp.PsmdRTkgxw/env/lib/python3.6/site-packages/lddwrap/__init__.py", line 113, in _strip_mem_address
text))
RuntimeError: Unexpected mem address. Expected to match ^\s*\(([^)]*)\)\s*$, but got: 'linked'
```

**Comment by mristin** [comment]
Hi @alexey-tereshenkov-oxb ,
Could you please test against the master that the PR #13 fixes your issue?

**Comment by mristin** [comment]
Pardon, maybe I misunderstood. Is that single line all output there is?

>
