### ISSUE TITLE
Can we have a new release?

### ISSUE THREAD

**Issue by thiagokokada** [Parquery/pylddwrap#29]
To include the fixes in https://github.com/Parquery/pylddwrap/pull/26.

CC @mristin.

**Comment by mristin** [comment]
Hi @thiagokokada ,
Sure! Sorry, my bad, the release slipped from the radar. I'll do it tomorrow morning CET.

**Comment by thiagokokada** [comment]
Sure, thanks @mristin.

**Comment by mristin** [comment]
Hi @thiagokokada ,
I have just published a new patch release 1.2.2 to PyPI. Please apologize the delay.
