### ISSUE TITLE
Add `--sorted` command-line option

### ISSUE THREAD

**Issue by mristin** [Parquery/pylddwrap#8]
Hi @sheerluck ,
I took insipration from your pull request #5 and implemented the feature in the separate pull request #7. I already merged the changes into the master branch. Could you please see if that works for you and there are any bugs or errors when you run it on your side?

If there are no bugs in a week, I'll bump the minor version.

(If you haven't done so, may I kindly ask you to star the project to give it visibility?)

**Comment by sheerluck** [comment]
`AssertionError` in `assert key is None or isinstance(key, (str, pathlib.Path))` **(main.py, line 82)** while sorting with `found` or `unused` when `key=False, type(key)=<class 'bool'>`

**Comment by sheerluck** [comment]
fix is trivial -- `isinstance(key, (str, bool, pathlib.Path))`

**Comment by mristin** [comment]
Thanks, @sheerluck ! I made a fix in PR #9 and merged it. Please let me know if you spot any further bugs :).

**Comment by sheerluck** [comment]
Everything is fine, thanks. I think this issue can be closed.

**Comment by mristin** [comment]
Hi @sheerluck ,
A minor version 1.1.0 including this feature has been released.
